server:
  port: 8888

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: http://auth-service.auth-service:8080
          predicates:
            - Path=/api/auth/**

        - id: product-service
          uri: http://product-service.product-service:8081
          predicates:
            - Path=/api/products/**

        - id: category-service
          uri: http://product-service.product-service:8081
          predicates:
            - Path=/api/categories/**

        - id: cart-service
          uri: http://cart-service.cart-service:8082
          predicates:
            - Path=/api/cart/**
