- name: Deploy Product Service
  hosts: all
  become: yes
  vars:
    docker_image_name: "{{ DOCKERHUB_USERNAME }}/product-service:latest"
    service_path: "/home/ubuntu/agent/workspace/ecommerce-microservices/product-service"

  tasks:
    - name: Login to Docker Hub
      shell: echo "{{ DOCKERHUB_PASSWORD }}" | docker login -u "{{ DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Product Docker image
      command: docker build -t {{ docker_image_name }} {{ service_path }}

    - name: Push Product Docker image
      command: docker push {{ docker_image_name }}

    - name: Run Product container
      shell: |
        docker rm -f product-service || true
        docker run -d --name product-service -p 8081:8081 {{ docker_image_name }}
