- name: Deploy Frontend Web
  hosts: all
  become: true
  vars:
    container_name: frontend-web
    image_name: dohuynhan/frontend-web:latest
    app_port: 80

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Login to Docker Hub
      shell: echo "{{ DOCKERHUB_PASSWORD }}" | docker login -u "{{ DOCKERHUB_USERNAME }}" --password-stdin
      register: login_result
      changed_when: "'Login Succeeded' in login_result.stdout"

    - name: Stop and remove old container if exists
      shell: docker rm -f {{ container_name }} || true

    - name: Pull latest Docker image
      shell: docker pull {{ image_name }}

    - name: Run new container
      shell: |
        docker run -d \
          --name {{ container_name }} \
          -p {{ app_port }}:{{ app_port }} \
          --restart unless-stopped \
          {{ image_name }}