- name: Deploy Auth Service
  hosts: all
  become: yes
  tasks:
    - name: Login to Docker Hub
      shell: echo "{{ lookup('env','DOCKERHUB_PASSWORD') }}" | docker login -u "{{ lookup('env','DOCKERHUB_USERNAME') }}" --password-stdin

    - name: Build Auth Docker image
      command: docker build -t dohuynhan/auth-service:latest ../authentication-service

    - name: Push Auth Docker image
      command: docker push dohuynhan/auth-service:latest

    - name: Run Auth container
      shell: |
        docker rm -f auth-service || true
        docker run -d --name auth-service -p 8080:8080 dohuynhan/auth-service:latest
